server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /var/www/html;
  index index.html;

  location /api/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Request-ID $http_x_request_id;
    proxy_pass http://localhost:3000;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
